# Generated by Django 2.1.5 on 2020-05-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200406_1032'),
        ('shop', '0003_auto_20190816_1348'),
    ]

    operations = [
    ]
